import { requireCtx } from "@/lib/auth";
import { redirect, notFound } from "next/navigation";
import { all, get } from "@/lib/db";
import { docPaid } from "@/lib/domain";
import { money } from "@/lib/util";
import DocToolbar from "./DocToolbar";

export const dynamic = "force-dynamic";

const TITLE: Record<string, string> = {
  sales_invoice: "SALES INVOICE", purchase_bill: "PURCHASE BILL", quotation: "QUOTATION",
  sales_return: "SALES RETURN", purchase_return: "PURCHASE RETURN",
};

export default async function DocView({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const ctx = await requireCtx();
  if (!ctx) redirect("/login");
  const bid = ctx.business.id;
  const sym = ctx.business.currency_symbol;

  const doc = get<{ id: string; kind: string; number: number; date: string; notes: string | null; subtotal: number; discount_total: number; tax_total: number; total: number; status: string; payment_mode: string | null; party_id: string | null }>(
    "SELECT * FROM documents WHERE id = ? AND business_id = ?", [id, bid]
  );
  if (!doc) notFound();
  const party = doc.party_id ? get<{ name: string; phone: string | null; address: string | null }>("SELECT name, phone, address FROM parties WHERE id = ?", [doc.party_id]) : null;
  const lines = all<{ name: string; qty: number; rate: number; discount_value: number; discount_type: string; tax_rate: number; amount: number }>(
    "SELECT name, qty, rate, discount_value, discount_type, tax_rate, amount FROM doc_items WHERE document_id = ?", [id]
  );
  const paid = docPaid(id);
  const due = Math.max(0, doc.total - paid);

  return (
    <div>
      <DocToolbar id={doc.id} kind={doc.kind} />
      <div className="card print-area" style={{ padding: "2rem", maxWidth: 760, margin: "0 auto" }}>
        <div style={{ display: "flex", justifyContent: "space-between", borderBottom: "2px solid var(--brand)", paddingBottom: "1rem" }}>
          <div>
            <div style={{ fontSize: "1.5rem", fontWeight: 800, color: "var(--brand)" }}>{ctx.business.name}</div>
            {ctx.business.address && <div className="text-muted" style={{ fontSize: ".85rem" }}>{ctx.business.address}</div>}
            {ctx.business.phone && <div className="text-muted" style={{ fontSize: ".85rem" }}>{ctx.business.phone}</div>}
          </div>
          <div style={{ textAlign: "right" }}>
            <div style={{ fontWeight: 800, letterSpacing: ".05em" }}>{TITLE[doc.kind]}</div>
            <div className="text-muted" style={{ fontSize: ".85rem" }}>#{doc.number}</div>
            <div className="text-muted" style={{ fontSize: ".85rem" }}>{doc.date}</div>
          </div>
        </div>

        <div style={{ margin: "1rem 0", fontSize: ".9rem" }}>
          <div className="text-muted">Bill To:</div>
          <div style={{ fontWeight: 700 }}>{party?.name || "Cash Sale"}</div>
          {party?.phone && <div className="text-muted">{party.phone}</div>}
          {party?.address && <div className="text-muted">{party.address}</div>}
        </div>

        <table className="tbl" style={{ marginTop: ".5rem" }}>
          <thead><tr><th>Item</th><th style={{ textAlign: "right" }}>Qty</th><th style={{ textAlign: "right" }}>Rate</th><th style={{ textAlign: "right" }}>Disc</th><th style={{ textAlign: "right" }}>Amount</th></tr></thead>
          <tbody>
            {lines.map((l, i) => (
              <tr key={i}>
                <td>{l.name}</td>
                <td style={{ textAlign: "right" }}>{l.qty}</td>
                <td style={{ textAlign: "right" }}>{money(l.rate, sym)}</td>
                <td style={{ textAlign: "right" }}>{l.discount_type === "percent" ? `${l.discount_value}%` : money(l.discount_value, sym)}</td>
                <td style={{ textAlign: "right", fontWeight: 600 }}>{money(l.amount, sym)}</td>
              </tr>
            ))}
          </tbody>
        </table>

        <div style={{ display: "flex", justifyContent: "flex-end", marginTop: "1rem" }}>
          <div style={{ width: 280, display: "grid", gap: ".3rem", fontSize: ".9rem" }}>
            <Row l="Sub Total" v={money(doc.subtotal, sym)} />
            <Row l="Discount" v={"− " + money(doc.discount_total, sym)} />
            <Row l="Tax" v={money(doc.tax_total, sym)} />
            <Row l="Total" v={money(doc.total, sym)} bold />
            {doc.kind !== "quotation" && <><Row l="Paid" v={money(paid, sym)} /><Row l="Due" v={money(due, sym)} bold /></>}
          </div>
        </div>

        {doc.notes && <div style={{ marginTop: "1.5rem", fontSize: ".85rem" }}><b>Notes:</b> {doc.notes}</div>}
        <div className="text-muted" style={{ marginTop: "2rem", fontSize: ".8rem", textAlign: "center" }}>Generated by Hishab</div>
      </div>
    </div>
  );
}

function Row({ l, v, bold }: { l: string; v: string; bold?: boolean }) {
  return (
    <div style={{ display: "flex", justifyContent: "space-between", fontWeight: bold ? 800 : 400, borderTop: bold ? "1px solid var(--border)" : undefined, paddingTop: bold ? ".2rem" : 0 }}>
      <span className={bold ? "" : "text-muted"}>{l}</span><span>{v}</span>
    </div>
  );
}
